### ISSUE TITLE
mkdir(): File exists error

### ISSUE THREAD

**Issue by boxybird** [TitasGailius/laravel-moonlight#10]
Running `php artisan ui moonlight --auth` on a fresh Laravel 7.19.0 install, I'm getting this error:

![Annotation 2020-07-07 153956](https://user-images.githubusercontent.com/18317878/86851989-c60b9100-c068-11ea-8f31-f11f3db2663b.png)

Any thoughts? I'm sure I'm missing something.

**Comment by TitasGailius** [comment]
Fixed in `1.0.2`.
