### ISSUE TITLE
Plans to update to fortify?

### ISSUE THREAD

**Issue by devingray** [TitasGailius/laravel-moonlight#12]
Hi @TitasGailius 

I wonder if you have any plans to update this to use Laravel Fortify Auth instead of the custom controllers. I know There is already Jetstream but TBH I like to build my own components. 

If this is something you are thinking to do with this package, happy to help

**Comment by TitasGailius** [comment]
Hey @devingray,

yeah, I think that's a great idea.

The only customization this package has for the auth stuff is overriding which views to show.

In Fortify, it's all about registering these views in a service provider so I think that's would be a fairly simple change to this package.

```php
use Laravel\Fortify\Fortify;

Fortify::loginView(function () {
    return view('auth.login');
});
```

For me personally, there are no gains of using Fortify over `laravel/ui` scaffolding but I'd be more than happy to accept a PR that uses Fortify.

**Comment by devingray** [comment]
💯 Awesome, I will look into that this week, I think super simple approach, perhaps a --fortify flag that will not render the routes and instead load them in the service provider. Will see as I go

**Comment by devingray** [comment]
Closing until fortify is more docmented
