### ISSUE TITLE
Uncaught ( in promise ) TypeError: n.swapComponent is not a function at app.js

### ISSUE THREAD

**Issue by OGhawsi** [TitasGailius/laravel-moonlight#16]
This is a great package, I reall appreciate the work. 

Fresh laravel 8 installation, and laravel moonlight installation throws this error in the console. 
**Uncaught ( in promise ) TypeError: n.swapComponent is not a function at app.js**

App is compiled successfully with no errors.

Thanks in advance.

**Comment by SerjoA** [comment]
i think i had the same error with vue3 and inertia and i fixed it with older inertia version and vue2

**Comment by OGhawsi** [comment]
The whole point of this package is to make the developer life easier by providing vue, tailwind and innertia. If we are forced to set up things manually then this package won't be much of a help. 
And I hope this issue is resolved.
