### ISSUE TITLE
Property in vue file

### ISSUE THREAD

**Issue by Wit3** [TitasGailius/laravel-moonlight#4]
Hi,
Thank you for this awesome repo.
I've a question, in the login.vue (resources/js/pages/auth/login.vue ) file at line 43 

`        layout: require('../../layouts/app').default, `

You assign the require layout file at the variabile named "layout"

Can you provide the documentation about this implementation?

Thanks

**Comment by TitasGailius** [comment]
https://inertiajs.com/pages

**Comment by Wit3** [comment]
Thanks
